### ISSUE TITLE
Semantic css is missing its image assets

### ISSUE THREAD

**Issue by olymk2** [agusmakmun/dracos-markdown-editor#1]
when trying to run collectstatic with the gzip storage engine, it errors when processing semantic.min.css.

because the flags.png file is not present so it fails to compress and stops the collect static process.

Its looking for a child path of the below in the css file.

themes/default/assets/images/flags.png

**Comment by agusmakmun** [comment]
Good catch, if I following your PR: #2 why you not change this `themes/default/assets/images/flags.png` to `../images/flags.png` inside file of `semantic.min.css` ?

**Comment by olymk2** [comment]
Happy to do that, does mean you will need to update the CSS file when ever
you update, not sure which is better I will leave it to your discretion,
happy to change it

**Comment by agusmakmun** [comment]
yes, I suggest you to change it, and put your `flags.png` image, into `/static/plugins/images/flags.png`. I hope you edit your pulled request that you created before.. I'll merge soon..

**Comment by olymk2** [comment]
okay, i will try and do this later today.

**Comment by olymk2** [comment]
files changed, and i rebuilt my containers and did not get an error so you should be good to merge if your happy

**Comment by lubo** [comment]
The problem has been reintroduced in ca2b64070c7554fe3a7c8241eeee6fc5e5cfaba1.
