### ISSUE TITLE
Syntax highlighting doesn't work in page view with template tags?

### ISSUE THREAD

**Issue by peidaqi** [agusmakmun/dracos-markdown-editor#8]
It seems that the syntax highlighting doesn't work with template tages. For example, with:
```
{% load dractags %}
{{ content | safe_makrdown }}

```
where content is:
```
```python

import numpy as np

import matplotlib.pyplot as plt

x = np.random.randn(100)

y = np.random.randn(100)

plt.plot(x, y) 

\```
```
only surrounds the string wiht <code></code>, but doesn't really render any of the hljs tags.

I wonder if I'm doing something wrong or simply this feature is not available (I copied the default settings from front page, using django 1.11 final).

Thanks!

**Comment by lyyyuna** [comment]
@peidaqi 
You can open the 'app/templates/test_markdownify.html' for reference.

**Comment by peidaqi** [comment]
Well unfortunately that file has no code blocks ...

**Comment by agusmakmun** [comment]
@peidaqi you only can provide a markdown styntax from backend to use the templatetags. like this https://github.com/agusmakmun/dracos-markdown-editor/blob/master/draceditor_demo/app/views.py#L30

**Comment by nathanfonbuena** [comment]
I'm running into this same problem with the newest version. Is there anyway to maintain syntax highlighting when displaying the saved information in a template tag?
