### ISSUE TITLE
Is there a way to change the highlight css style? e.g. github code style

### ISSUE THREAD

**Issue by xianfuxing** [agusmakmun/dracos-markdown-editor#9]
I found the highlight html code is not the same as the original markdown + Pygments.
So can not use the exist github.css from markdown plugin.

**Comment by agusmakmun** [comment]
@xianfuxing you can see this [example](https://github.com/agusmakmun/dracos-markdown-editor/blob/master/draceditor_demo/app/templates/test_markdownify.html), and [this css](https://github.com/agusmakmun/dracos-markdown-editor/blob/master/draceditor/static/draceditor/css/draceditor.css#L135-L258). you can integrate it with github style.
